meta:                                       
    site_title: "熊猫人Blog"
    site_subtitle: "熊猫人Blog主题：感想,敢拼,敢赢..."
    site_language: "en"
    absolute_baseurl: http://demi-panda.com
    domain: demi-panda.com
    author:
        full_name: demi-panda.com
        short_name: demi-panda
        name: 
        email: demi-panda@126.com

url: http://demi-panda.com
#baseurl: /
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
auto: true
debug: false

