meta:                                       
    site_title: "Demi Panda Blogs"
    site_subtitle: "Demi 古希腊平民,人民的代名词, Panda 现实生活中高贵,权利的象征."
    site_language: "zh-cn"
    absolute_baseurl: http:/demi-panda.com/blog
    domain: demi-panda.com
    author:
        full_name: demi-panda.com
        short_name: demi-panda
        name: 
        email: demi-panda@126.com

baseurl: 
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
auto: true
#debug: false




