meta:                                       
    site_title: "熊猫人Blog"
    site_subtitle: "熊猫人Blog主题：敢想,敢拼,敢赢..."
    site_content: "个人博客,IT技术,研发实践,互联网,资讯,创业,搜索引擎,Lucene,Solr,Java,生活,旅游"
    site_language: "CN"
    absolute_baseurl: http://demi-panda.com
    domain: demi-panda.com
    author:
        full_name: demi-panda.com
        short_name: demi-panda
        name: 
        email: demi-panda@126.com

url: http://demi-panda.com
#baseurl: /
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
auto: true
debug: false

