meta:                                       
    site_title: "熊猫家族"
    site_subtitle: "熊猫家族博客：敢想,敢拼,敢赢..."
    site_content: "博客,IT技术,研发实践,互联网,资讯,编程语言,搜索引擎,Lucene,Solr,Java,生活,旅游,吃货,熊猫吃货,微生活,健康,美食"
    site_language: "CN"
    absolute_baseurl: http://demi-panda.com
    domain: demi-panda.com
    defualt_limit: 50
    author:
        full_name: demi-panda.com
        short_name: demi-panda
        name: 
        email: demi-panda@126.com

url: http://demi-panda.com
baseurl:
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
auto: true
debug: true

links:
    - url: "http://lusongsong.com/"
      name: 卢松松
      title: 关注站长和搜索引擎的IT博客
    - url: "http://www.muchangqing.com/"
      name: 牟长青
      title: 牟长青的网站推广博客
    - url: "http://coolshell.cn/"
      name: 酷壳
      title: 享受编程和技术所带来的快乐
    - url: "http://yanping.me/"
      name: 雁起平沙
      title: 雁起平沙的网络日志
    - url: "http://www.letuknowit.com/"
      name: 知蚁博客
      title:
    - url: "http://www.zhangyuchang.com/"
      name: 不纯粹文人
      title: 不经一番寒彻骨，哪得梅花扑鼻香
    - url: "http://chenpeng.info/"
      name: 陈鹏个人博客
    - url: "http://www.kandisheng.com/"
      name: 不霁何虹博客
    - url: "http://blog.jobbole.com/"
      name: 伯乐在线
