meta:                                       
    site_title: "熊猫家族"
    site_subtitle: "熊猫家族博客：敢想,敢拼,敢赢..."
    site_content: "博客,IT技术,研发实践,互联网,资讯,编程语言,搜索引擎,Lucene,Solr,Java,生活,旅游,吃货,熊猫吃货,微生活,健康,美食"
    site_language: "CN"
    absolute_baseurl: http://demi-panda.com
    domain: demi-panda.com
    defualt_limit: 50
    emergency_news: "熊猫家族博客新版本上线,欢迎大家交流"
    author:
        full_name: denghaiping
        short_name: denghp
        name: 
        email: denghp@126.com

aliyun_oss: http://demi-panda.oss.aliyuncs.com
#base_url: http://demi-panda.com
base_url:
baseurl: 
markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
auto: true
debug: true

countPerPage: 15
tags_max_item: 200
links:
    - url: "http://lusongsong.com/"
      name: 卢松松博客
      title: 关注站长和搜索引擎的IT博客
    - url: "http://coolshell.cn/"
      name: 酷壳
      title: 享受编程和技术所带来的快乐
    - url: "http://yanping.me/"
      name: 雁起平沙
      title: 雁起平沙的网络日志
    - url: "http://www.letuknowit.com/"
      name: 知蚁博客
    - url: "http://blog.jobbole.com/"
      name: 伯乐在线
    - url: "http://cn.technode.com/"
      name: 动点科技
    - url: "http://www.blogbus.com/"
      name: 博客大巴
    - url: "http://asiachrispy.github.io/itec"
      name: 黄忠的技术博客
